### ISSUE TITLE
Feedback received from LFE team on 18th oct 2023

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/lfeteach#85] opened 2023-10-18 10:33 UTC
- [x] under more section Demo video link is updated on prod, this has be updated on UAT as well, before we move the next task mentioned below.

- [x] This card changes are to be moved to prod: https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/lfeteach/82

after doing above 2 task, below activity has to be started

The feedback sheet was updated with the below points which are to be resolved on priority on Production org as the filed activity is planned on 20th Oct 2023. 
UAT org: Teachnluat (@teachnluat)
prod org: Teach nangaland (@teachnl)

Feedback sheet for reference: https://docs.google.com/spreadsheets/d/1GLQf0BGXvS6BalYi04qZtUU34NsadQV04t3bh7o7SZA/edit#gid=338542167

- [x] Question: Replace Type of School with " The Teach tool manual to be followed for this observation: "
In the Answer : replace "Primary" with "Teach Primary" or Replace "Secondary" with "Teach Secondary"

PS: The answer should be auto-displayed based on the grade selected by the observer
Uploaded asset
this point was done on UAT, but this hasn't moved when UAT bundle was moved to prod old card for reference: https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/lfeteach/78

- [x] The hint option "?" to see the description for L,M,H etc is not visible. basically, for each response, a hint option use to get displayed "?" on the observations form against the questions to help the user understand what response options, this icon is not visible on prod and user is not able to take help on that information.
- [x] The "Overall overview" session in the "More" page is displaying an error for few users. For the rest of the users element list with a 0 avg score is displayed as it should be.

**Comment by BEULAHEVANJALIN** [comment] 2023-10-19 07:29
The person who worked on the dashboard card, used "const" to declare score2 varible, but later in the code, they tried to reassign it with some value if it's null or undefined. This is not allowed for variables declared with const. We should have used "let" instead.

---

Following are the cards that need changes:
- [ ] Supportive learning environment
- [ ] Positive behavioural expectations
- [ ] Lesson facilitation
- [ ] Checks for understanding
- [ ] Feedback
- [ ] Critical thinking
- [ ] Autonomy
- [ ] Perseverance
- [ ] Social and collaborative skills

**Comment by Dinesh2019** [comment] 2023-10-19 13:48
The issue is reproducible decisiom segment 2 - class size is the displayed even after the skip logic is given as yes 

Steps to reproduce:
1.register the teacher
2.Continue the observation at the segment 1 : skip logic question click as no and proceed to next page
3.Click on the previous and then click on yes skip the segment 2 
4.select the date of next observation 
5.Move to summary page u can see the segement 2 - class size


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3RTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b81e076cb73806a7e539790e0b2a5c0c28186dc4/repord.mp4

**Comment by salilsamanvay** [comment] 2023-10-20 06:29
@BEULAHEVANJALIN @Dinesh2019 translation of Hindi is reflecting in devnagri font it should be written in English only.

[Uploading... Screenshot 2023-10-20 at 11.55.07 AM.png]

rest all is fine..

**Comment by Dinesh2019** [comment] 2023-10-20 07:23
@Salil the translation is done and looks good fine for me 

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEZZQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--436b0f3e77d9caf72e37b1620c5f8d644897af3c/image.png

**Closed** 2023-10-20 09:12 UTC
